development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>_development
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DATABASE_NAME'] %>_test
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  database: d65kpl6njkmhv7
  host: ec2-54-221-253-228.compute-1.amazonaws.com
  port: 5432
  username: zigmatsxaaffvt
  password: 6abca07588bb7a8e8ae2d0dfb722f403ce8849a9aa6b8456fc9712ee7a9f76cd